name: Docker image build and push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u "maanavdocker" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t maanavdocker/fastapi-app:latest .
          docker push maanavdocker/fastapi-app:latest
